java:
  image: 'hmctspublic.azurecr.io/am/org-role-mapping-service:latest'
  ingressHost: am-org-role-mapping-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4098
  aadIdentityName: am
  
  keyVaults:
    am:
      secrets:
        - AppInsightsInstrumentationKey
        - am-org-role-mapping-service-s2s-secret
        - role-assignment-service-LD-SDK-KEY
        - orm-IDAM-CLIENT-ID
        - orm-IDAM-CLIENT-SECRET
        - orm-IDAM-ADMIN-SECRET
        - caseworker-topic-primary-send-listen-shared-access-key
  
  environment:
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_USER_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    OIDC_ISSUER_URL: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AM_ORG_ROLE_MAPPING_S2S_AUTHORISED_SERVICES: ccd_gw,am_org_role_mapping_service,am_role_assignment_service
    ROLE_ASSIGNMENT_APP_URL: http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASE_WORKER_REF_APP_URL: http://rd-caseworker-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"
    AMQP_HOST: rd-servicebus-{{ .Values.global.environment }}.servicebus.windows.net
    AMQP_SHARED_ACCESS_KEY_NAME: SendAndListenSharedAccessKey
    AMQP_TOPIC_NAME: rd-caseworker-topic-{{ .Values.global.environment }}/subscriptions/rd-caseworker-subscription-{{ .Values.global.environment }}
    TRUST_ALL_CERTS: "true"

servicebus:
  enabled: false