java:
  image: 'hmctspublic.azurecr.io/am/org-role-mapping-service:latest'
  ingressHost: am-org-role-mapping-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4098
  aadIdentityName: am
  autoscaling:
    enabled: false
  keyVaults:
    am:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: am-org-role-mapping-service-s2s-secret
          alias: AM_ORG_ROLE_MAPPING_SERVICE_SECRET
        - name: role-assignment-service-LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: orm-IDAM-CLIENT-ID
          alias: ORM_IDAM_CLIENT_ID
        - name: orm-IDAM-CLIENT-SECRET
          alias: ORG_ROLE_MAPPING_IDAM_CLIENT_SECRET
        - name: orm-IDAM-ADMIN-SECRET
          alias: ORG_ROLE_MAPPING_IDAM_ADMIN_PASSWORD
        - name: caseworker-topic-primary-send-listen-shared-access-key
          alias: AMQP_CRD_SHARED_ACCESS_KEY_VALUE
        - name: org-role-mapping-service-POSTGRES-PASS
          alias: ORG_ROLE_MAPPING_DB_PASSWORD
        - name: judicial-topic-primary-send-listen-shared-access-key
          alias: AMQP_JRD_SHARED_ACCESS_KEY_VALUE
  environment:
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_USER_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    OIDC_ISSUER_URL: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AM_ORG_ROLE_MAPPING_S2S_AUTHORISED_SERVICES: ccd_gw,am_org_role_mapping_service,am_role_assignment_service,xui_webapp,am_role_assignment_refresh_batch
    ROLE_ASSIGNMENT_APP_URL: http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    JUDICIAL_BOOKING_APP_URL: http://am-judicial-booking-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASE_WORKER_REF_APP_URL: http://rd-caseworker-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    JUDICIAL_REF_APP_URL: http://rd-judicial-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"
    AMQP_HOST: rd-servicebus-{{ .Values.global.environment }}.servicebus.windows.net
    AMQP_SHARED_ACCESS_KEY_NAME: SendAndListenSharedAccessKey
    AMQP_ENABLED: true
    TRUST_ALL_CERTS: "true"
    CRD_TOPIC_NAME: rd-caseworker-topic-{{ .Values.global.environment }}
    CRD_SUBSCRIPTION_NAME: rd-caseworker-subscription-{{ .Values.global.environment }}
    JRD_TOPIC_NAME: rd-judicial-topic-{{ .Values.global.environment }}
    JRD_SUBSCRIPTION_NAME: rd-judicial-subscription-{{ .Values.global.environment }}
    ORG_ROLE_MAPPING_IDAM_ADMIN_USERID: orm.admin@hmcts.NET
    ORG_ROLE_MAPPING_DB_PORT: 5432
    ORG_ROLE_MAPPING_DB_NAME: org_role_mapping
    ORG_ROLE_MAPPING_DB_HOST: am-org-role-mapping-service-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    ORG_ROLE_MAPPING_DB_USERNAME: am@am-org-role-mapping-service-postgres-db-v11-{{ .Values.global.environment }}
    ORG_ROLE_MAPPING_DB_OPTIONS: "?stringtype=unspecified&sslmode=require"
    REFRESH_JOB:
    TESTING_SUPPORT_ENABLED: false
    APPLICATION_LOGGING_LEVEL: INFO
    RUN_LD_ON_STARTUP: true

#subcharts conditions
orm:
  ras:
    enabled: false
  jbs:
    enabled: false
  servicebus:
    enabled: false
