java:
  image: 'hmctspublic.azurecr.io/am/org-role-mapping-service:latest'
  ingressHost: am-org-role-mapping-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4098
  aadIdentityName: am
  keyVaults:
    am:
      secrets:
        - AppInsightsInstrumentationKey
        - am-org-role-mapping-service-s2s-secret
        - role-assignment-service-LD-SDK-KEY
  environment:
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_USER_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    OIDC_ISSUER_URL: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AM_ORG_ROLE_MAPPING_S2S_AUTHORISED_SERVICES: ccd_gw,am_org_role_mapping_service
    ROLE_ASSIGNMENT_APP_URL: http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASE_WORKER_REF_APP_URL: http://rd-caseworker-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"
    ORG_ROLE_MAPPING_IDAM_CLIENT_ID: am_role_assignment
    MICROSERVICE_NAME: am_role_assignment_service