spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:${wiremock.server.port:5000}/o

idam:
  s2s-auth:
    url: http://localhost:${wiremock.server.port:4502}
  api.url: http://localhost:${wiremock.server.port:5000}

feign:
  client:
    config:
      crdclient:
        url: http://localhost:${wiremock.server.port:8095}
      roleAssignmentApp:
        url: http://localhost:${wiremock.server.port:4096}
      jrdClient:
        url: http://localhost:${wiremock.server.port:8091}
      jbsClient:
        url: http://localhost:${wiremock.server.port:4097}
